name: test-check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - run: npm i jest
      - run: NODE_OPTIONS=--experimental-vm-modules npx jest

  